Repository sdpython/onnxcustom, pull requests merged in 2021-12, with the labels that each got.

#19 Implements training with forward, backward
  _doc/examples/plot_orttraining_linear_regression_partial.py
  _doc/sphinxdoc/source/api/data_loader.rst
  _doc/sphinxdoc/source/api/plotting.rst
  _doc/sphinxdoc/source/api/training.rst
  _doc/sphinxdoc/source/api/utils.rst
  _doc/sphinxdoc/source/conf.py
  _doc/sphinxdoc/source/tutorial/index.rst
  _doc/sphinxdoc/source/tutorial/tutorial_6_training.rst
  _doc/sphinxdoc/source/tutorial/tutorial_6_training_partial.rst
  _unittests/ut_training/test_data_loader.py
  _unittests/ut_training/test_optimizers.py
  _unittests/ut_training/test_orttraining_forward_backward.py
  onnxcustom/training/data_loader.py
  onnxcustom/training/optimizers.py
  onnxcustom/training/ortgradient.py
  onnxcustom/training/orttraining.py
  requirements-dev.txt
Labels: enhancement

#22 Move learning_rate logic in a separate class
  _doc/sphinxdoc/source/api/training.rst
  _doc/sphinxdoc/source/onnxmd/index.rst
  _unittests/ut_training/test_optimizers.py
  onnxcustom/training/optimizers.py
  onnxcustom/training/sgd_learning_rate.py
Labels: enhancement

#23 Extend documentation
  _doc/sphinxdoc/source/onnxmd/index.rst
  _doc/sphinxdoc/source/onnxmd/index_onnx.rst
  _doc/sphinxdoc/source/onnxmd/index_onnxruntime.rst
  _doc/sphinxdoc/source/onnxmd/onnx_add_new_op.rst
  _doc/sphinxdoc/source/onnxmd/onnx_changelog.rst
  _doc/sphinxdoc/source/onnxmd/onnx_changelog_ml.rst
  _doc/sphinxdoc/source/onnxmd/onnx_contributing.rst
  _doc/sphinxdoc/source/onnxmd/onnx_docs/Broadcasting.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/CONTRIBUTING.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/Changelog-ml.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/Hub.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/IR.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/MetadataProps.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/ONNXTypes.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/OnnxReleases.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/Operators-ml.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/PythonAPIOverview.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/ShapeInference.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/Syntax.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/TestCoverage-ml.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/Versioning.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/proposals/ArchiveFileFormatProposal.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/proposals/NLPinONNXproposal.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/proposals/ONNXIFIproposal.md
  _doc/sphinxdoc/source/onnxmd/onnx_docs/proposals/SymbolicShapeInfProposal.md
  _doc/sphinxdoc/source/onnxmd/onnx_managing.rst
  _doc/sphinxdoc/source/onnxmd/onnx_metadata.rst
  _doc/sphinxdoc/source/onnxmd/onnx_operators.rst
  _doc/sphinxdoc/source/onnxmd/onnx_operators_ml.rst
  _doc/sphinxdoc/source/onnxmd/onnx_releases.rst
  _doc/sphinxdoc/source/onnxmd/onnx_test_coverage.rst
  _doc/sphinxdoc/source/onnxmd/onnx_test_coverage_ml.rst
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/ABI_Dev_Notes.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/Android_testing.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/C_API_Guidelines.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/Coding_Conventions_and_Standards.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/ContribOperators.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/FAQ.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/How_To_Update_ONNX_Dev_Notes.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/Model_Test.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/ONNX_Runtime_Server_Usage.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/OperatorKernels.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/PR_Guidelines.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/Privacy.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/Python_Dev_Notes.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/Roadmap.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/Server.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/Versioning.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/WinML_principles.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/cmake_guideline.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_docs/onnxruntime_extensions.md
  _doc/sphinxdoc/source/onnxmd/onnxruntime_python/exceptions.rst
  _doc/sphinxdoc/source/onnxmd/onnxruntime_python/helpers.rst
  _doc/sphinxdoc/source/onnxmd/onnxruntime_python/inference.rst
  _doc/sphinxdoc/source/onnxmd/onnxruntime_python/ortvalue.rst
  _doc/sphinxdoc/source/onnxmd/onnxruntime_python/sparse.rst
  _doc/sphinxdoc/source/onnxmd/onnxruntime_python/training.rst
  _doc/sphinxdoc/source/onnxmd/onnxruntime_python/training_partial.rst
Labels: documentation

#27 Uses C_OrtDevice everywhere
  _doc/examples/plot_benchmark_op_leakyrelu.py
  _doc/examples/plot_benchmark_op_short.py
  _doc/sphinxdoc/source/conf.py
  _doc/sphinxdoc/source/tutorial_onnx/challenges.rst
  _doc/sphinxdoc/source/tutorial_onnx/concepts.rst
  _unittests/ut_training/test_optimizers_forward_backward.py
  _unittests/ut_training/test_orttraining_forward_backward.py
  _unittests/ut_utils/test_onnxruntime_helper.py
  onnxcustom/training/data_loader.py
  onnxcustom/training/optimizers.py
  onnxcustom/training/optimizers_partial.py
  onnxcustom/training/ortgradient.py
  onnxcustom/utils/onnxruntime_helper.py
Labels: refactoring

#28 Replaces OrtValue by C_OrtValue everywhere
  _doc/examples/plot_benchmark_op.py
  _doc/examples/plot_benchmark_op_short.py
  _doc/examples/plot_orttraining_linear_regression_gpu.py
  _unittests/ut_training/test_orttraining_forward_backward.py
  _unittests/ut_utils/test_print_helper.py
  onnxcustom/training/data_loader.py
  onnxcustom/training/ortgradient.py
  onnxcustom/utils/onnxruntime_helper.py
  onnxcustom/utils/print_helper.py
Labels: refactoring

#29 Fixes #16, support weights while training
  _unittests/ut_training/test_data_loader.py
  _unittests/ut_training/test_optimizers.py
  _unittests/ut_training/test_optimizers_forward_backward.py
  _unittests/ut_utils/test_onnx_function.py
  onnxcustom/training/data_loader.py
  onnxcustom/training/optimizers.py
  onnxcustom/training/optimizers_partial.py
  onnxcustom/utils/onnx_function.py
  onnxcustom/utils/onnx_helper.py
  onnxcustom/utils/onnx_orttraining.py
Labels: enhancement
