Repository sdpython/onnxcustom, pull requests merged in 2022-11, with the labels that each got.

#67 Add one more example about TfidfVectorizer
  _doc/examples/plot_transformer_discrepancy.py
  _doc/examples/plot_usparse_xgboost.py
  _doc/sphinxdoc/source/tutorials/tutorial_skl/tutorial_1_simple.rst
  _doc/sphinxdoc/source/tutorials/tutorial_skl/tutorial_4_complex.rst
Labels: documentation

#68 Adds an example to check parallel execution
  .circleci/config.yml
  .gitignore
  _doc/examples/data/ort_cpu_gpu.csv
  _doc/examples/data/ort_gpus.csv
  _doc/examples/plot_parallel_execution.py
  _doc/sphinxdoc/source/api/onnxruntime_python/index.rst
  _doc/sphinxdoc/source/conf.py
  _doc/sphinxdoc/source/tutorials/tutorial_onnxruntime/ortvalue_doc.rst
  _unittests/ut_documentation/test_documentation_examples_lightgbm.py
  onnxcustom/utils/onnx_function.py
Labels: documentation

#69 Updates OrtGradientForwardBackward to support the latest onnxruntime
  onnxcustom/training/ortgradient.py
Labels: bug

#70 Modifies one example about parallel execution
  .gitignore
  _doc/examples/data/ort_cpu_gpu.csv
  _doc/examples/data/ort_gpus.csv
  _doc/examples/data/ort_gpus_gpt2.csv
  _doc/examples/plot_parallel_execution.py
Labels: documentation

#71 Splits onnx models
  .circleci/config.yml
  .gitignore
  _doc/examples/data/ort_cpu_gpu.csv
  _doc/examples/data/ort_gpus.csv
  _doc/examples/data/ort_gpus_gpt2.csv
  _doc/examples/data/ort_gpus_piece.csv
  _doc/examples/data/ort_gpus_piece_resnet18.csv
  _doc/examples/plot_parallel_execution.py
  _doc/examples/plot_parallel_execution_big_model.py
  _doc/sphinxdoc/source/api/utils.rst
  _unittests/ut_documentation/test_documentation_examples_parallel.py
  _unittests/ut_utils/test_onnxruntime_helper.py
  _unittests/ut_utils/test_split_onnx.py
  azure-pipelines.yml
  onnxcustom/training/grad_helper.py
  onnxcustom/utils/benchmark.py
  onnxcustom/utils/onnx_split.py
  onnxcustom/utils/onnxruntime_helper.py
Labels: enhancement

#72 Support for custom cutting points
  _doc/examples/data/ort_gpus_piece_resnet18.csv
  _doc/examples/plot_parallel_execution_big_model.py
  _doc/sphinxdoc/source/tutorials/index.rst
  _doc/sphinxdoc/source/tutorials/tutorial_parallel/index.rst
  _unittests/ut_utils/test_split_onnx.py
  onnxcustom/utils/onnx_split.py
Labels: enhancement

#73 Update CI
  .circleci/config.yml
  appveyor.yml
  azure-pipelines.yml
Labels: ci

#75 Supports small inputs in onnx_split
  _unittests/ut_utils/test_split_onnx.py
  onnxcustom/utils/onnx_split.py
Labels: bug

#77 Adds an example to benchmark a kind of eager mode
  _doc/examples/data/eager_mode.csv
  _doc/examples/plot_benchmark_eager_mode.py
  _doc/examples/plot_benchmark_onnx_function.py
  _doc/examples/plot_benchmark_ort_api.py
  _doc/sphinxdoc/source/conf.py
  _doc/sphinxdoc/source/tutorials/tutorial_bench/tutorial_benchmark.rst
Labels: documentation

#78 Uses new method run_with_ortvaluevector
  .gitignore
  _doc/examples/data/plot_benchmark_eager_mode.csv
  _doc/examples/plot_benchmark_eager_mode.py
  _doc/sphinxdoc/source/tutorials/tutorial_parallel/index.rst
Labels: documentation
