Repository sdpython/onnxcustom, pull requests merged in 2022-02, with the labels that each got.

#51 Implements scoring functions
  _doc/sphinxdoc/source/api/index.rst
  _doc/sphinxdoc/source/api/training_utils.rst
  _unittests/ut_training/test_gradient_mlp.py
  _unittests/ut_training/test_optimizers_forward_backward.py
  _unittests/ut_training/test_optimizers_grid_score.py
  _unittests/ut_utils/test_onnx_function.py
  onnxcustom/training/__init__.py
  onnxcustom/training/_base_estimator.py
  onnxcustom/training/excs.py
  onnxcustom/training/optimizers.py
  onnxcustom/training/optimizers_partial.py
  onnxcustom/training/sgd_learning_loss.py
  onnxcustom/training/sgd_learning_rate.py
  onnxcustom/utils/onnx_function.py
  onnxcustom/utils/onnx_rewriter.py
Labels: enhancement

#53 Implements get_trained_onnx to retrieve the trained model
  _doc/sphinxdoc/source/api/training_utils.rst
  _unittests/ut_training/test_optimizers_classification.py
  onnxcustom/training/_base_estimator.py
  onnxcustom/training/optimizers.py
  onnxcustom/training/optimizers_partial.py
  onnxcustom/utils/onnx_helper.py
Labels: enhancement

#55 Clean gradient with unnecessary nodes
  _unittests/ut_training/test_grad_helper.py
  onnxcustom/training/grad_helper.py
Labels: bug

#56 Renames Z into Y_grad in loss functions returning grad
  _unittests/ut_training/test_optimizers_classification.py
  _unittests/ut_training/test_optimizers_forward_backward.py
  _unittests/ut_training/test_optimizers_nan.py
  _unittests/ut_utils/test_onnx_function.py
  onnxcustom/training/sgd_learning_loss.py
  onnxcustom/utils/onnx_function.py
Labels: refactoring

#57 Fix opset for ai.onnx.ml in examples after updating to onnx==1.11
  _doc/examples/plot_abegin_convert_pipeline.py
  _doc/examples/plot_bbegin_measure_time.py
  _doc/examples/plot_catwoe_transformer.py
  _doc/examples/plot_dbegin_options_zipmap.py
  _doc/examples/plot_gbegin_cst.py
  _doc/examples/plot_gexternal_lightgbm.py
  _doc/examples/plot_gexternal_lightgbm_reg.py
  _doc/examples/plot_gexternal_xgboost.py
  _doc/examples/plot_mcustom_parser.py
  _doc/examples/plot_mcustom_parser_dataframe.py
  _doc/examples/plot_usparse_xgboost.py
  _doc/notebooks/tree_to_onnx.ipynb
  _unittests/ut_plotting/test_plotting_onnx.py
  onnxcustom/utils/cst.py
  onnxcustom/utils/onnx_function.py
Labels: bug
