Repository sdpython/onnxcustom, pull requests merged in 2022-01, with the labels that each got.

#33 Implements more loss functions
  _doc/bench/bench_orttraining_nn_gpu.py
  _doc/bench/bench_orttraining_nn_gpu_fwbw.py
  _doc/examples/plot_orttraining_benchmark.py
  _doc/examples/plot_orttraining_linear_regression.py
  _doc/examples/plot_orttraining_linear_regression_fwbw.py
  _doc/examples/plot_orttraining_nn_gpu.py
  _doc/examples/plot_orttraining_nn_gpu_fwbw.py
  _doc/examples/plot_orttraining_nn_gpu_fwbw_nesterov.py
  _doc/sphinxdoc/source/api/training.rst
  _unittests/ut_training/test_optimizers.py
  _unittests/ut_utils/test_onnx_orttraining.py
  onnxcustom/training/base_onnx_function.py
  onnxcustom/training/optimizers.py
  onnxcustom/training/optimizers_partial.py
  onnxcustom/training/ortgradient.py
  onnxcustom/training/sgd_learning_rate.py
  onnxcustom/utils/onnx_orttraining.py
  onnxcustom/utils/orttraining_helper.py
Labels: enhancement

#34 Implements L1, L2 losses for partial training
  _doc/examples/plot_orttraining_linear_regression.py
  _doc/examples/plot_orttraining_linear_regression_fwbw.py
  _doc/examples/plot_orttraining_nn_gpu.py
  _doc/sphinxdoc/source/api/training.rst
  _doc/sphinxdoc/source/api/utils.rst
  _doc/sphinxdoc/source/tutorial_training/tutorial_6_training.rst
  _doc/sphinxdoc/source/tutorial_training/tutorial_6_training_partial.rst
  _unittests/ut_training/test_optimizers_forward_backward.py
  _unittests/ut_utils/test_onnx_function.py
  onnxcustom/training/base_onnx_function.py
  onnxcustom/training/optimizers.py
  onnxcustom/training/optimizers_partial.py
  onnxcustom/training/ortgradient.py
  onnxcustom/training/sgd_learning_loss.py
  onnxcustom/training/sgd_learning_penalty.py
  onnxcustom/training/sgd_learning_rate.py
  onnxcustom/utils/onnx_function.py
  onnxcustom/utils/onnxruntime_helper.py
Labels: enhancement

#35 Reduces the number of calls to bind_ortvalue
  _doc/bench/bench_orttraining_nn_gpu_fwbw.py
  _doc/sphinxdoc/source/tutorial_training/tutorial_6_training_partial.rst
  _unittests/ut_utils/test_onnxruntime_helper.py
  _unittests/ut_utils/test_print_helper.py
  onnxcustom/plotting/plotting_onnx.py
  onnxcustom/training/base_onnx_function.py
  onnxcustom/training/optimizers_partial.py
  onnxcustom/training/ortgradient.py
  onnxcustom/training/sgd_learning_loss.py
  onnxcustom/training/sgd_learning_penalty.py
  onnxcustom/training/sgd_learning_rate.py
  onnxcustom/utils/doc_helper.py
  onnxcustom/utils/onnx_function.py
  onnxcustom/utils/onnx_helper.py
  onnxcustom/utils/onnxruntime_helper.py
Labels: performance

#36 Makes sure all plt.show() have been disabled in examples
  _unittests/ut_documentation/test_documentation_examples_show.py
Labels: documentation

#37 Improves performance of caching
  onnxcustom/training/base_onnx_function.py
Labels: performance

#41 Refactors to improve profiling analysis (fix penalty, export onnx graphs)
  _doc/examples/plot_orttraining_nn_gpu_fwbw_nesterov.py
  _doc/sphinxdoc/source/tutorial_training/tutorial_6_training_partial.rst
  _unittests/ut_training/test_optimizers_forward_backward.py
  _unittests/ut_utils/test_onnx_function.py
  onnxcustom/training/_base.py
  onnxcustom/training/base_estimator.py
  onnxcustom/training/base_onnx_function.py
  onnxcustom/training/optimizers_partial.py
  onnxcustom/training/ortgradient.py
  onnxcustom/training/sgd_learning_loss.py
  onnxcustom/training/sgd_learning_penalty.py
  onnxcustom/training/sgd_learning_rate.py
  onnxcustom/utils/onnx_function.py
Labels: refactoring

#42 Implements binary log loss for first API of orttraining
  .circleci/config.yml
  .gitignore
  _doc/examples/plot_funny_sigmoid.py
  _doc/sphinxdoc/source/api/training.rst
  _doc/sphinxdoc/source/tutorial_onnxruntime/training_ort_api.rst
  _doc/sphinxdoc/source/tutorial_skl/tutorial_1_simple.rst
  _doc/sphinxdoc/source/tutorial_training/tutorial_6_training_partial.rst
  _unittests/ut_module/test_onnx_runtimes.py
  _unittests/ut_training/test_optimizers.py
  _unittests/ut_training/test_optimizers_classification.py
  _unittests/ut_training/test_orttraining_forward_backward.py
  _unittests/ut_utils/test_onnx_function.py
  _unittests/ut_utils/test_onnx_helper.py
  _unittests/ut_utils/test_onnx_orttraining.py
  _unittests/ut_utils/test_onnx_writer.py
  _unittests/ut_utils/test_orttraining_helper.py
  appveyor.yml
  onnxcustom/training/_base.py
  onnxcustom/training/_base_estimator.py
  onnxcustom/training/_base_onnx_function.py
  onnxcustom/training/optimizers.py
  onnxcustom/training/optimizers_partial.py
  onnxcustom/training/ortgradient.py
  onnxcustom/training/sgd_learning_loss.py
  onnxcustom/training/sgd_learning_penalty.py
  onnxcustom/training/sgd_learning_rate.py
  onnxcustom/utils/onnx_function.py
  onnxcustom/utils/onnx_helper.py
  onnxcustom/utils/onnx_rewriter.py
  onnxcustom/utils/orttraining_helper.py
Labels: enhancement

#43 Fixes the training of a binary classifier with weights
  _unittests/ut_training/test_optimizers_classification.py
  _unittests/ut_utils/test_onnx_function.py
  onnxcustom/utils/onnx_function.py
Labels: bug

#44 Uses bind_ortvalue_input instead of bind_input to be faster
  _unittests/ut_training/test_optimizers_classification.py
  onnxcustom/training/optimizers.py
Labels: performance

#45 Adds an example about classification
  _doc/examples/plot_orttraining_benchmark_fwbw_cls.py
  _doc/sphinxdoc/source/tutorial_training/tutorial_6_training_partial.rst
  onnxcustom/training/data_loader.py
  onnxcustom/utils/orttraining_helper.py
Labels: documentation

#48 Checks gradients are identical to scikit-learn for neural networks
  _doc/examples/plot_orttraining_benchmark_fwbw_cls.py
  _unittests/ut_documentation/test_documentation_check_coverage.py
  _unittests/ut_documentation/test_documentation_examples_benchmark.py
  _unittests/ut_documentation/test_documentation_examples_lightgbm.py
  _unittests/ut_documentation/test_documentation_examples_training.py
  _unittests/ut_documentation/test_documentation_examples_training_fwbw.py
  _unittests/ut_documentation/test_documentation_examples_training_torch.py
  _unittests/ut_documentation/test_documentation_examples_u.py
  _unittests/ut_documentation/test_documentation_examples_u_.py
  _unittests/ut_documentation/test_documentation_notebooks.py
  _unittests/ut_module/test_onnx_runtimes.py
  _unittests/ut_plotting/test_plotting_onnx.py
  _unittests/ut_training/test_gradient_mlp.py
  _unittests/ut_training/test_optimizers.py
  _unittests/ut_training/test_optimizers_classification.py
  _unittests/ut_training/test_optimizers_forward_backward.py
  _unittests/ut_utils/test_onnx_function.py
  _unittests/ut_utils/test_onnx_helper.py
  _unittests/ut_utils/test_onnx_writer.py
  _unittests/ut_utils/test_orttraining_helper.py
  appveyor.yml
  onnxcustom/training/optimizers_partial.py
  onnxcustom/training/sgd_learning_loss.py
  onnxcustom/utils/onnx_function.py
Labels: enhancement

#49 Check nan values during training
  _unittests/ut_training/test_optimizers_nan.py
  onnxcustom/training/optimizers.py
  onnxcustom/training/optimizers_partial.py
  onnxcustom/training/sgd_learning_rate.py
Labels: bug
