Repository sdpython/onnxcustom, pull requests merged in 2023-02, with the labels that each got.

#86 Implementations for float 8 conversion
  _doc/examples/plot_f8.py
  _doc/sphinxdoc/source/api/experiment.rst
  _doc/sphinxdoc/source/api/index.rst
  _doc/sphinxdoc/source/tutorials/tutorial_training/index.rst
  _doc/sphinxdoc/source/tutorials/tutorial_training/tutorial_7_related_topics.rst
  _unittests/ut_experiment/test_f8.py
  _unittests/ut_module/test_code_style.py
  onnxcustom/experiment/__init__.py
  onnxcustom/experiment/f8.py
Labels: enhancement

#87 Implements conversion with E5M2
  _doc/examples/plot_f8.py
  _doc/sphinxdoc/source/api/experiment.rst
  _unittests/ut_experiment/test_f8.py
  onnxcustom/experiment/f8.py
Labels: enhancement

#88 Fixes backward propagation for shape results
  _unittests/ut_experiment/test_f8.py
  _unittests/ut_utils/test_split_onnx.py
  onnxcustom/experiment/f8.py
  onnxcustom/utils/onnx_split.py
Labels: bug

#90 Improves float 8 functions and documentation
  _doc/examples/plot_f8.py
  onnxcustom/experiment/f8.py
Labels: documentation
